---
- hosts: web-servers
  user: vagrant
  sudo: True

  vars:
    # Base path for includes and files
    # Must be set to absolute path of playbooks directory
    base: /path/to/playbooks
    env: dev # Set to dev or prod

  vars_files:
    - $base/apache/vars.yml
    - $base/mysql/vars.yml
    - $base/php/vars.yml
    - $base/varnish/vars.yml
    - $base/jenkins/vars.yml
    - provision_overrides/${env}_vars.yml

  tasks:
    # -= REQUIRED =-
    - include: $base/common/setup.yml

    # -= OPTIONAL =-
    - include: $base/apache/setup.yml
    - include: $base/drush/setup.yml
    - include: $base/mysql/setup.yml
    - include: $base/mongodb/setup.yml
    - include: $base/node/setup.yml
    - include: $base/php/setup.yml
    - include: $base/phpcs/setup.yml
    - include: $base/redis/setup.yml
    - include: $base/ruby-css/setup.yml
    - include: $base/tools/setup.yml
    - include: $base/varnish/setup.yml
    - include: $base/jenkins/setup.yml
  # - include: provision_overrides/setup.yml

  handlers:
    # -= OPTIONAL =-
    - include: $base/apache/handler.yml
    - include: $base/mysql/handler.yml
    - include: $base/mongodb/handler.yml
    - include: $base/tools/handler.yml
    - include: $base/varnish/handler.yml
    - include: $base/jenkins/handler.yml
