---
- hosts: $hosts
  user: $user

  vars-files:
    - vars.yml

  tasks:
    - name: apt-get update
      action: apt update-cache=yes

    - include: setup.yml

  handlers:
    - include: handler.yml
