---
- hosts: webservers
  user: $user

  vars:
    bind_address: "127.0.0.1"
    key_buffer: "16M"
    max_packet: "32M"
    max_open_files: "65534"

  tasks:
    - name: update apt repo
      action: apt update-cache=yes

    - include: setup.yml

  handlers:
    - include: handler.yml
