---
- hosts: webservers
  user: $user

  vars_files:
    - vars.yml

  tasks:
    - name: update apt repo
      action: apt update-cache=yes

    - include: setup.yml

  handlers:
    - include: handler.yml
